### ISSUE TITLE
Is there a particular reason lists have a special highlight color?

### ISSUE THREAD

**Issue by bschlagel** [sn-extensions/minimal-markdown-editor#15]
With the default theme, list text appears blue (very similar to standard hyperlink color); seems distracting and can't see a reason for it being highlighted at all; I think preferable to just be same color as body text like it is in the advanced markdown editor.

**Comment by mobitar** [comment]
We colorize certain CodeMirror classes, and some classes are used in multiple places, like in code and in lists (like `.cm-variable`, iirc). I'll have to take another look at this and see if we can exclude some styles for lists.

**Comment by y0ns0n** [comment]
For lists in particular it looks like it might be the `.cm-variable-3` class.

**Comment by adriantombu** [comment]
Bumping this too one year later as I still encounter the problem, which is really annoying and distracting 😁

**Comment by mobitar** [comment]
cc @ningsongshen

**Comment by MorgothSauron** [comment]
I'm late to the party, but I actually like the current color 'scheme' in the minimal markdown editor, especially the different color for the 1st two level in the list (blue then green)

**Comment by mobitar** [comment]
It might be likable by some but I think is too subjective overall and not typical/expected with Markdown.

**Comment by adriantombu** [comment]
Thanks for the update, would it be possible to publish a new release to get the updates in SN ? 🤗

**Comment by mobitar** [comment]
Released, please give a few minutes to propagate 👍
