### ISSUE TITLE
No text highlight with theme enabled

### ISSUE THREAD

**Issue by half0wl** [sn-extensions/minimal-markdown-editor#2]
Text highlights are invisible on Minimal and Advanced Markdown Editor with the following themes: Futura, Midnight, Focused. Seems to be okay with Titanium.

**Comment by mobitar** [comment]
This is fixed in the 2.1 beta.

**Comment by half0wl** [comment]
Yup, seems to be fixed in 2.1. I'm closing this.

Thanks for your hard work, it looks like everything is coming together quite nicely :-)

**Comment by mobitar** [comment]
Great!
