### ISSUE TITLE
Doesn't render note when its empty.

### ISSUE THREAD

**Issue by fahrradflucht** [sn-extensions/minimal-markdown-editor#3]
After switching to an empty note the editor pane retains the previous selected notes content.

Edit:
I debugged this some more. Looks like an empty note created with SN Web/Desktop has an empty string as content while an empty note created with the android app has `undefined` as content. The above described bug occurs only with the android sourced notes. So maybe the real issue is this client behaviour mismatch.

Sidenote:
I would have expected the batch editor to show an empty text property field for the web client note (like `Text: `) and no text property field for the android note. But it hides the field completely in both cases.

**Comment by mobitar** [comment]
Wait so can you describe the steps required to duplicate this? I'm getting a little mixed up with the steps required on desktop and mobile.

**Comment by fahrradflucht** [comment]
1. Create a note with no content on android
2. Switch to desktop sn.
2. Set minimal-markdown-editor as default editor (er enable it for both notes involved)
3. Open another note with content.
4. Switch to the note created on android.

**Expected Behaviour:**
The editor pane is empty.

**Actual Behaviour:**
The editor pane will retain the content.

**Comment by mobitar** [comment]
I tested this just now but am still a little confused.

1. How are you creating a blank note on Android? It really doesn't let you. If you press new but don't enter any content, then go back, it does not save that note. 
2. What version of the Android app are you using?
3. If you "4. Open another note with content", then "5. "Switch to [empty] note created on android", wouldn't you expect to see blank content?

**Comment by fahrradflucht** [comment]
1. You have to create a title. Just no content.
2. 2.1.2
3. Yes this is what I wrote...

**Comment by mobitar** [comment]
Ah, gotcha. Good catch. Was able to replicate the issue.

**Comment by mobitar** [comment]
This is fixed in the upcoming 2.1.26 release.
