### ISSUE TITLE
Sublists still render green

### ISSUE THREAD

**Issue by christianhans** [sn-extensions/minimal-markdown-editor#30]
<img width="350" alt="Screen Shot 2020-07-25 at 3 18 08 PM" src="https://user-images.githubusercontent.com/355541/88464587-174dba00-ce8a-11ea-8991-a07cdacaae24.png">

**Comment by JaspalSuri** [comment]
Hi, Christain. Thanks for letting us know! I was able to reproduce this as well and will make sure the team's aware of this issue.

**Comment by MorgothSauron** [comment]
Is this really a bug ? Because it's been like this since I started to use SN and this is my default editor. 

<img width="179" alt="image" src="https://user-images.githubusercontent.com/6804228/88632689-776b7880-d0a3-11ea-95a1-bf8f41f2e4a0.png">

I think the current color scheme for this editor is just fine and doe not need to be changed.

**Comment by mobitar** [comment]
We were able to get level one list items changed to default text color, but as anticipated, that CSS selector (`cm-variable-2`) is shared by `code blocks`, so those lost their blue tint. There still does not appear to be a way to differentiate list items from regular CodeMirror elements, so I still don't see a way to stylize nested list items with a more neutral text color.

**Comment by ningsongshen** [comment]
I just checked the code earlier and code blocks user a different selector: `cm-comment`. It might be possible to fix the indented list items, but I'll need to check on the side effects.

**Comment by MorgothSauron** [comment]
@mobitar @JaspalSuri  Why this is being changed ? I consider the current colors as a feature of the editor. Minimal markdown is my main editor and using only black text for list will screw up the "look & feel" of this editor.
